export const TOGGLE_ORDERS_ADD_EDIT_FORM = 'TOGGLE_ORDERS_ADD_EDIT_FORM';
export const TOGGLE_CUSTOMERS_ADD_EDIT_FORM = 'TOGGLE_CUSTOMERS_ADD_EDIT_FORM';
export const TOGGLE_FOODS_ADD_EDIT_FORM = 'TOGGLE_FOODS_ADD_EDIT_FORM';
