export const TOGGLE_ORDERS_ADD_EDIT_FORM = 'TOGGLE_ORDERS_ADD_EDIT_FORM';
export const TOGGLE_CUSTOMERS_ADD_EDIT_FORM = 'TOGGLE_CUSTOMERS_ADD_EDIT_FORM';
export const TOGGLE_FOODS_ADD_EDIT_FORM = 'TOGGLE_FOODS_ADD_EDIT_FORM';
export const TOGGLE_WEEKLY_MENUS_ADD_EDIT_FORM = 'TOGGLE_WEEKLY_MENUS_ADD_EDIT_FORM';

// foodsAction
export const FETCH_FOODS_REQUEST = 'FETCH_FOODS_REQUEST';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAIL = 'FETCH_FOODS_FAIL';

export const POST_FOODS_REQUEST = 'POST_FOODS_REQUEST';
export const POST_FOODS_SUCCESS = 'POST_FOODS_SUCCESS';
export const POST_FOODS_FAIL = 'POST_FOODS_FAIL';

export const PUT_FOODS_REQUEST = 'PUT_FOODS_REQUEST';
export const PUT_FOODS_SUCCESS = 'PUT_FOODS_SUCCESS';
export const PUT_FOODS_FAIL = 'PUT_FOODS_FAIL';

export const DELETE_FOODS_REQUEST = 'DELETE_FOODS_REQUEST';
export const DELETE_FOODS_SUCCESS = 'DELETE_FOODS_SUCCESS';
export const DELETE_FOODS_FAIL = 'DELETE_FOODS_FAIL';

// customersAction
export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';

export const POST_CUSTOMERS_REQUEST = 'POST_CUSTOMERS_REQUEST';
export const POST_CUSTOMERS_SUCCESS = 'POST_CUSTOMERS_SUCCESS';
export const POST_CUSTOMERS_FAIL = 'POST_CUSTOMERS_FAIL';

export const PUT_CUSTOMERS_REQUEST = 'PUT_CUSTOMERS_REQUEST';
export const PUT_CUSTOMERS_SUCCESS = 'PUT_CUSTOMERS_SUCCESS';
export const PUT_CUSTOMERS_FAIL = 'PUT_CUSTOMERS_FAIL';

export const DELETE_CUSTOMERS_REQUEST = 'DELETE_CUSTOMERS_REQUEST';
export const DELETE_CUSTOMERS_SUCCESS = 'DELETE_CUSTOMERS_SUCCESS';
export const DELETE_CUSTOMERS_FAIL = 'DELETE_CUSTOMERS_FAIL';

// schoolsAction
export const FETCH_SCHOOLS_REQUEST = 'FETCH_SCHOOLS_REQUEST';
export const FETCH_SCHOOLS_SUCCESS = 'FETCH_SCHOOLS_SUCCESS';
export const FETCH_SCHOOLS_FAIL = 'FETCH_SCHOOLS_FAIL';

export const POST_SCHOOLS_REQUEST = 'POST_SCHOOLS_REQUEST';
export const POST_SCHOOLS_SUCCESS = 'POST_SCHOOLS_SUCCESS';
export const POST_SCHOOLS_FAIL = 'POST_SCHOOLS_FAIL';

export const PUT_SCHOOLS_REQUEST = 'PUT_SCHOOLS_REQUEST';
export const PUT_SCHOOLS_SUCCESS = 'PUT_SCHOOLS_SUCCESS';
export const PUT_SCHOOLS_FAIL = 'PUT_SCHOOLS_FAIL';

export const DELETE_SCHOOLS_REQUEST = 'DELETE_SCHOOLS_REQUEST';
export const DELETE_SCHOOLS_SUCCESS = 'DELETE_SCHOOLS_SUCCESS';
export const DELETE_SCHOOLS_FAIL = 'DELETE_SCHOOLS_FAIL';
