export const TOGGLE_ORDERS_ADD_EDIT_FORM = 'TOGGLE_ORDERS_ADD_EDIT_FORM';
export const TOGGLE_CUSTOMERS_ADD_EDIT_FORM = 'TOGGLE_CUSTOMERS_ADD_EDIT_FORM';
export const TOGGLE_FOODS_ADD_EDIT_FORM = 'TOGGLE_FOODS_ADD_EDIT_FORM';
export const TOGGLE_WEEKLY_MENUS_ADD_EDIT_FORM = 'TOGGLE_WEEKLY_MENUS_ADD_EDIT_FORM';

// foodsAction
export const FETCH_FOODS_REQUEST = 'FETCH_FOODS_REQUEST';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAIL = 'FETCH_FOODS_FAIL';

export const POST_FOODS_REQUEST = 'POST_FOODS_REQUEST';
export const POST_FOODS_SUCCESS = 'POST_FOODS_SUCCESS';
export const POST_FOODS_FAIL = 'POST_FOODS_FAIL';

export const PUT_FOODS_REQUEST = 'PUT_FOODS_REQUEST';
export const PUT_FOODS_SUCCESS = 'PUT_FOODS_SUCCESS';
export const PUT_FOODS_FAIL = 'PUT_FOODS_FAIL';

export const DELETE_FOODS_REQUEST = 'DELETE_FOODS_REQUEST';
export const DELETE_FOODS_SUCCESS = 'DELETE_FOODS_SUCCESS';
export const DELETE_FOODS_FAIL = 'DELETE_FOODS_FAIL';
